FROM python:3.11-slim

# 1. Set the root of the app
WORKDIR /app

# 2. Tell Python that /app is the base for all imports
ENV PYTHONPATH=/app

# 3. Install requirements first (for faster builds)
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader punkt wordnet

# 4. Copy your entire project into /app
# This means your folder structure inside Docker will be /app/src/main.py
COPY . .

# 5. The Command
# We use 'src.main:app' because we are at the /app level
CMD ["sh", "-c", "uvicorn src.main:app --host 0.0.0.0 --port ${PORT:-8000}"]